[env:esp32dev]
platform = espressif32@~6.10.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
    bogde/HX711
    bblanchon/ArduinoJson
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include
